# Generated by Django 4.1.5 on 2023-02-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulletinBoard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquery",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
