# Generated by Django 4.1.5 on 2023-02-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bulletinBoard", "0002_alter_inquery_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="parent_reply",
        ),
    ]
