# Generated by Django 4.1.7 on 2023-03-08 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bulletinBoard", "0004_alter_reply_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquery",
            options={"ordering": ["created_at"]},
        ),
    ]
