# Generated by Django 4.1.7 on 2023-03-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletinBoard", "0005_alter_inquery_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquery",
            name="state",
            field=models.CharField(
                choices=[("N", "미응답"), ("Y", "응답"), ("P", "추가의문"), ("F", "처리완료")],
                default="N",
                max_length=1,
            ),
        ),
    ]
