# Generated by Django 4.1.5 on 2023-01-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="accounts/%Y/%m/%d"),
        ),
    ]
