# Generated by Django 4.1.5 on 2023-01-09 18:31

from django.db import migrations, models
import sbd_animal.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[sbd_animal.accounts.models.validate_username],
            ),
        ),
    ]
