# Generated by Django 4.1.5 on 2023-01-11 11:37

from django.db import migrations, models
import sbd_animal.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", sbd_animal.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="your email"
            ),
        ),
    ]
