# Generated by Django 4.1.5 on 2023-02-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_out", "0002_log_percentile"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="num_sets",
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
