# Generated by Django 4.1.5 on 2023-02-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_out", "0003_log_num_sets"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={"ordering": ["-id", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="rep",
            options={"ordering": ["-id", "rep_order_number"]},
        ),
    ]
